name: Tests

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install pre-commit
    - name: Lint code
      run: pre-commit run --all-files