name: Tests

on:
  pull_request:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install pre-commit
    - name: Lint code
      run: pre-commit run --all-files

  test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version:
            - '3.8'
          metaflow-version:
            - '2.7.18'
            - '2.7.19'
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: pip install -r requirements.txt ".[dev]"
        - name: Install specific metaflow version for test
          run: pip install metaflow==${{matrix.metaflow-version}}
        - name: Run tests
          run: pytest tests/